version: '3.8'

services:
  flask_app:
    replicas: 6
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_container
    ports:
      - "5005:5000"
    environment:
      FLASK_ENV: production
    depends_on:
      - redis
      - db

  redis:
    replicas: 3
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6379:6379"

  db:
    replicas: 3
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
